import { createElement } from "react";
import DocsLayout from "../../components/DocsLayout.js";

export default function ComparisonPage() {
  return createElement(DocsLayout, null,

    createElement("h1", null, "Framework Comparison"),

    createElement("p", null,
      "Capstan combines a production-grade AI agent runtime with a full-stack web framework. ",
      "This page compares it with agent frameworks (LangChain, CrewAI, AutoGen) and web frameworks (Next.js, FastAPI)."
    ),

    // ── Capstan vs Agent Frameworks ──────────────────────────────────
    createElement("h2", null, "Capstan vs Agent Frameworks"),

    createElement("p", null,
      "Other agent frameworks give you building blocks. Capstan gives you a production-grade agent runtime with 30+ engineering features built in."
    ),

    createElement("table", null,
      createElement("thead", null,
        createElement("tr", null,
          createElement("th", null, "Feature"),
          createElement("th", null, "Capstan"),
          createElement("th", null, "LangChain"),
          createElement("th", null, "CrewAI"),
          createElement("th", null, "AutoGen")
        )
      ),
      createElement("tbody", null,
        createElement("tr", null,
          createElement("td", null, "Agent loop"),
          createElement("td", null, "Built-in ", createElement("code", null, "createSmartAgent")),
          createElement("td", null, "Custom chains"),
          createElement("td", null, "Custom"),
          createElement("td", null, "Custom")
        ),
        createElement("tr", null,
          createElement("td", null, "Tool validation"),
          createElement("td", null, "JSON Schema + custom ", createElement("code", null, "validate"), " hook"),
          createElement("td", null, "None"),
          createElement("td", null, "None"),
          createElement("td", null, "None")
        ),
        createElement("tr", null,
          createElement("td", null, "Tool timeout"),
          createElement("td", null, "Per-tool configurable (", createElement("code", null, "Promise.race"), ")"),
          createElement("td", null, "None"),
          createElement("td", null, "None"),
          createElement("td", null, "None")
        ),
        createElement("tr", null,
          createElement("td", null, "LLM watchdog"),
          createElement("td", null, "Chat timeout (120s) + stream idle (90s)"),
          createElement("td", null, "None"),
          createElement("td", null, "None"),
          createElement("td", null, "None")
        ),
        createElement("tr", null,
          createElement("td", null, "Model fallback"),
          createElement("td", null, "Automatic with thinking block stripping"),
          createElement("td", null, "Manual"),
          createElement("td", null, "None"),
          createElement("td", null, "Manual")
        ),
        createElement("tr", null,
          createElement("td", null, "Context compression"),
          createElement("td", null, "4-layer (snip / microcompact / autocompact / reactive)"),
          createElement("td", null, "None"),
          createElement("td", null, "None"),
          createElement("td", null, "None")
        ),
        createElement("tr", null,
          createElement("td", null, "Token budget"),
          createElement("td", null, "Nudge at 80% + force-complete at 100%"),
          createElement("td", null, "None"),
          createElement("td", null, "None"),
          createElement("td", null, "None")
        ),
        createElement("tr", null,
          createElement("td", null, "Tool result budget"),
          createElement("td", null, "Per-result + aggregate 200K + disk persistence"),
          createElement("td", null, "None"),
          createElement("td", null, "None"),
          createElement("td", null, "None")
        ),
        createElement("tr", null,
          createElement("td", null, "Skill layer"),
          createElement("td", null, createElement("code", null, "defineSkill"), " + ", createElement("code", null, "activate_skill"), " synthetic tool"),
          createElement("td", null, "None"),
          createElement("td", null, "Role prompts (partial)"),
          createElement("td", null, "None")
        ),
        createElement("tr", null,
          createElement("td", null, "Self-evolution"),
          createElement("td", null, "Experience -> Strategy -> Skill promotion"),
          createElement("td", null, "None"),
          createElement("td", null, "None"),
          createElement("td", null, "None")
        ),
        createElement("tr", null,
          createElement("td", null, "Error withholding"),
          createElement("td", null, "Retry once before exposing to LLM"),
          createElement("td", null, "None"),
          createElement("td", null, "None"),
          createElement("td", null, "None")
        ),
        createElement("tr", null,
          createElement("td", null, "Checkpoint / resume"),
          createElement("td", null, "Built-in with serializable state"),
          createElement("td", null, "Custom code"),
          createElement("td", null, "None"),
          createElement("td", null, "Custom code")
        ),
        createElement("tr", null,
          createElement("td", null, "Tool concurrency"),
          createElement("td", null, "Built-in concurrent dispatch"),
          createElement("td", null, "None"),
          createElement("td", null, "None"),
          createElement("td", null, "None")
        ),
        createElement("tr", null,
          createElement("td", null, "Stop hooks (guardrails)"),
          createElement("td", null, "Built-in with feedback loop"),
          createElement("td", null, "Custom code"),
          createElement("td", null, "None"),
          createElement("td", null, "None")
        ),
        createElement("tr", null,
          createElement("td", null, "Lifecycle hooks"),
          createElement("td", null, createElement("code", null, "onRunComplete"), ", ", createElement("code", null, "afterIteration"), ", ", createElement("code", null, "afterToolCall")),
          createElement("td", null, "None"),
          createElement("td", null, "None"),
          createElement("td", null, "None")
        ),
        createElement("tr", null,
          createElement("td", null, "Full-stack web"),
          createElement("td", null, "React SSR + HTTP + MCP + A2A + OpenAPI"),
          createElement("td", null, "None"),
          createElement("td", null, "None"),
          createElement("td", null, "None")
        )
      )
    ),

    createElement("h3", null, "When to use Capstan over LangChain / CrewAI / AutoGen"),
    createElement("ul", null,
      createElement("li", null, "You want an agent runtime where validation, timeout, compression, fallback, skills, and evolution are first-class configuration -- not custom wrapper code"),
      createElement("li", null, "You need a full-stack framework underneath: database, auth, policies, web UI"),
      createElement("li", null, "You want multi-protocol surfaces (HTTP, MCP, A2A, OpenAPI) from one definition"),
      createElement("li", null, "You need production hardening built in, not bolted on after launch")
    ),

    createElement("h3", null, "When to use LangChain / CrewAI / AutoGen over Capstan"),
    createElement("ul", null,
      createElement("li", null, "You need Python-first LLM orchestration with a large connector ecosystem"),
      createElement("li", null, "You are building multi-agent role-based workflows (CrewAI)"),
      createElement("li", null, "You need conversational multi-agent patterns with shared state (AutoGen)"),
      createElement("li", null, "Your project is agent logic only, with no web application layer")
    ),

    // ── Capstan vs Web Frameworks ────────────────────────────────────
    createElement("h2", null, "Capstan vs Web Frameworks"),

    createElement("table", null,
      createElement("thead", null,
        createElement("tr", null,
          createElement("th", null, "Feature"),
          createElement("th", null, "Capstan"),
          createElement("th", null, "Next.js"),
          createElement("th", null, "FastAPI")
        )
      ),
      createElement("tbody", null,
        createElement("tr", null,
          createElement("td", null, "Primary audience"),
          createElement("td", null, "Human users + AI agents"),
          createElement("td", null, "Human users"),
          createElement("td", null, "API consumers")
        ),
        createElement("tr", null,
          createElement("td", null, "API definition"),
          createElement("td", null, createElement("code", null, "defineAPI()"), " with Zod schemas"),
          createElement("td", null, "Route handlers"),
          createElement("td", null, "Pydantic models")
        ),
        createElement("tr", null,
          createElement("td", null, "Multi-protocol"),
          createElement("td", null, "HTTP + MCP + A2A + OpenAPI from one definition"),
          createElement("td", null, "HTTP only"),
          createElement("td", null, "HTTP + OpenAPI")
        ),
        createElement("tr", null,
          createElement("td", null, "Agent manifest"),
          createElement("td", null, "Auto-generated at ", createElement("code", null, "/.well-known/capstan.json")),
          createElement("td", null, "Not available"),
          createElement("td", null, "Not available")
        ),
        createElement("tr", null,
          createElement("td", null, "MCP server"),
          createElement("td", null, "Built-in (", createElement("code", null, "capstan mcp"), ")"),
          createElement("td", null, "Not available"),
          createElement("td", null, "Not available")
        ),
        createElement("tr", null,
          createElement("td", null, "A2A protocol"),
          createElement("td", null, "Built-in"),
          createElement("td", null, "Not available"),
          createElement("td", null, "Not available")
        ),
        createElement("tr", null,
          createElement("td", null, "OpenAPI spec"),
          createElement("td", null, "Auto-generated from Zod schemas"),
          createElement("td", null, "Requires third-party tools"),
          createElement("td", null, "Built-in")
        ),
        createElement("tr", null,
          createElement("td", null, "Server runtime"),
          createElement("td", null, "Hono (Web Standards)"),
          createElement("td", null, "Custom (Turbopack/Webpack)"),
          createElement("td", null, "Uvicorn/ASGI")
        ),
        createElement("tr", null,
          createElement("td", null, "Database"),
          createElement("td", null, "Drizzle ORM with ", createElement("code", null, "defineModel()")),
          createElement("td", null, "BYO (Prisma, Drizzle, etc.)"),
          createElement("td", null, "BYO (SQLAlchemy, etc.)")
        ),
        createElement("tr", null,
          createElement("td", null, "Auth"),
          createElement("td", null, "Built-in JWT + API key for agents"),
          createElement("td", null, "NextAuth.js (community)"),
          createElement("td", null, "BYO")
        ),
        createElement("tr", null,
          createElement("td", null, "Policy engine"),
          createElement("td", null, createElement("code", null, "definePolicy()"), " with allow/deny/approve/redact"),
          createElement("td", null, "Not available"),
          createElement("td", null, "Not available")
        ),
        createElement("tr", null,
          createElement("td", null, "Smart agent runtime"),
          createElement("td", null, createElement("code", null, "createSmartAgent"), " with 30+ features"),
          createElement("td", null, "Not available"),
          createElement("td", null, "Not available")
        ),
        createElement("tr", null,
          createElement("td", null, "Skill layer + evolution"),
          createElement("td", null, createElement("code", null, "defineSkill"), " + evolution engine"),
          createElement("td", null, "Not available"),
          createElement("td", null, "Not available")
        ),
        createElement("tr", null,
          createElement("td", null, "Ecosystem maturity"),
          createElement("td", null, "Early stage"),
          createElement("td", null, "Mature, large ecosystem"),
          createElement("td", null, "Mature")
        )
      )
    ),

    createElement("h3", null, "When to use Capstan over Next.js"),
    createElement("ul", null,
      createElement("li", null, "You are building an application that AI agents will interact with programmatically"),
      createElement("li", null, "You want a single ", createElement("code", null, "defineAPI()"), " call to generate HTTP, MCP, A2A, and OpenAPI endpoints"),
      createElement("li", null, "You need human-in-the-loop approval workflows for agent actions"),
      createElement("li", null, "You want built-in agent authentication (API keys) alongside human auth (JWT)"),
      createElement("li", null, "You need a smart agent runtime with production-grade tool execution")
    ),

    createElement("h3", null, "When to use Next.js over Capstan"),
    createElement("ul", null,
      createElement("li", null, "You are building a primarily human-facing web application"),
      createElement("li", null, "You need React Server Components or edge runtime"),
      createElement("li", null, "You rely on the Next.js ecosystem (Vercel, middleware, etc.)"),
      createElement("li", null, "Your project requires mature community support and extensive documentation")
    ),

    createElement("h3", null, "When to use FastAPI over Capstan"),
    createElement("ul", null,
      createElement("li", null, "You are building a Python API with automatic OpenAPI generation"),
      createElement("li", null, "You need the Python ML/data science ecosystem"),
      createElement("li", null, "Your project is API-only with no web UI requirements")
    ),

    // ── Feature Comparison Table ─────────────────────────────────────
    createElement("h2", null, "Feature Comparison Table"),
    createElement("p", { className: "table-legend" },
      createElement("span", { className: "check" }, "+"),
      " Built-in  ",
      createElement("span", { className: "partial" }, "~"),
      " Partial / Plugin  ",
      createElement("span", { className: "cross" }, "-"),
      " Not available"
    ),
    createElement("table", null,
      createElement("thead", null,
        createElement("tr", null,
          createElement("th", null, "Feature"),
          createElement("th", null, "Capstan"),
          createElement("th", null, "Next.js"),
          createElement("th", null, "FastAPI"),
          createElement("th", null, "LangChain"),
          createElement("th", null, "CrewAI"),
          createElement("th", null, "AutoGen")
        )
      ),
      createElement("tbody", null,
        createElement("tr", null,
          createElement("td", null, "HTTP API framework"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "MCP server (auto-generated)"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "A2A protocol"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "OpenAPI auto-generation"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Agent manifest"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "File-based routing"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "React SSR"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Built-in database layer"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Built-in auth (JWT + API key)"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Policy engine"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "AI TDD verification"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Smart agent runtime"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Tool input validation"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Tool timeout (per-tool)"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "LLM watchdog / timeout"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Context compression (4-layer)"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Token budget management"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Skill layer"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "partial" }, "~"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Self-evolution"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Checkpoint / resume"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "partial" }, "~"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "partial" }, "~")
        ),
        createElement("tr", null,
          createElement("td", null, "Model fallback"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "partial" }, "~"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "partial" }, "~")
        ),
        createElement("tr", null,
          createElement("td", null, "LLM orchestration"),
          createElement("td", { className: "partial" }, "~"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "check" }, "+")
        ),
        createElement("tr", null,
          createElement("td", null, "Multi-agent workflows"),
          createElement("td", { className: "partial" }, "~"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "check" }, "+")
        ),
        createElement("tr", null,
          createElement("td", null, "TypeScript-first"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "check" }, "+"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "partial" }, "~"),
          createElement("td", { className: "cross" }, "-"),
          createElement("td", { className: "cross" }, "-")
        ),
        createElement("tr", null,
          createElement("td", null, "Production maturity"),
          createElement("td", null, "beta"),
          createElement("td", null, "mature"),
          createElement("td", null, "mature"),
          createElement("td", null, "early"),
          createElement("td", null, "early"),
          createElement("td", null, "early")
        )
      )
    ),

    // ── Key Insight ──────────────────────────────────────────────────
    createElement("h2", null, "Key Insight"),
    createElement("div", { className: "callout callout-info" },
      createElement("p", null,
        "Other agent frameworks give you building blocks. Capstan gives you a production-grade agent runtime with 30+ engineering features built in -- ",
        "validation, timeout, compression, fallback, skills, evolution, budgets, checkpoints, and lifecycle hooks -- alongside a full-stack web framework with multi-protocol API surfaces. No other framework combines both."
      )
    ),

    createElement("h2", null, "Summary"),
    createElement("div", { className: "callout callout-info" },
      createElement("p", null,
        createElement("strong", null, "Choose Capstan"), " when you need a production-grade AI agent runtime (with tool validation, compression, evolution, and 30+ built-in features) and/or a full-stack web framework with multi-protocol agent surfaces."
      ),
      createElement("p", null,
        createElement("strong", null, "Choose Next.js"), " when you are building a primarily human-facing web application and need the mature React ecosystem and Vercel integration."
      ),
      createElement("p", null,
        createElement("strong", null, "Choose FastAPI"), " when you are building a Python API with automatic OpenAPI generation and need the ML/data science ecosystem."
      ),
      createElement("p", null,
        createElement("strong", null, "Choose LangChain / CrewAI / AutoGen"), " when you need Python-first LLM orchestration, multi-agent role-based workflows, or graph-based state machines -- and do not need a web application framework."
      )
    )
  );
}
